language: python
python: 
  - "3.6"
branches:
  only:
    - master
    - develop
sudo: false
install: "pip install jsonschema"
script:

# check valid JSON/well formatted
- python3 test.py format
- git diff --quiet &>/dev/null

# check test schemas
- python3 test.py validate ./src/VMTestsFiller ./src/GeneralStateTestsFiller ./src/BlockchainTestsFiller ./VMTests ./GeneralStateTests ./BlockchainTests
